services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file: .env
    expose:
      - "443"
    ports: 
      - "443:443"
    networks: 
      - inception
    volumes:
      - nginx_www:/var/www/
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  nginx_www:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ~/goinfre/www/