services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file: ".env"
    expose:
      - "443"
    ports: 
      - "443:443"
    networks: 
      - inception
    volumes:
      - nginx_www:/var/www/
    restart: always

  mariadb:
    build:
      context: ./mariaDB
      dockerfile: Dockerfile
    container_name: mariaDB
    volumes:
      - mariaDB:/etc/mariaDB/
    env_file: ".env"
    expose:
      - "3306"
    ports: 
      - "3306:3306"
    networks: 
      - inception
    restart: always

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - nginx_www:/var/www/
    env_file: ".env"
    networks: 
      - inception
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  nginx_www:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ~/goinfre/www/
  mariaDB:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/mjochum/goinfre/mariaDB